<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProgramsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('programs')->delete();
        
        \DB::table('programs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'direccion_administrativa_id' => 16,
                'name' => 'ADMINISTRACION SECRETARIA DE ADMINISTRACION Y FINANZAS',
                'description' => '',
                'procedure_type_id' => 1,
                'class' => 'programa',
                'number' => '117',
                'programatic_category' => '00-0-001',
                'amount' => '23902557.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'direccion_administrativa_id' => 59,
                'name' => 'ADMINISTRACION ASAMBLEA DEPARTAMENTAL',
                'description' => '',
                'procedure_type_id' => 1,
                'class' => 'programa',
                'number' => '117',
                'programatic_category' => '01-0-001',
                'amount' => '8840672.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'direccion_administrativa_id' => 32,
            'name' => 'SERVICIOS DEPARTAMENTALES DE SALUD (TGN)',
                'description' => '',
                'procedure_type_id' => 1,
                'class' => 'programa',
                'number' => '117',
                'programatic_category' => '40-0-020',
                'amount' => '245436514.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'direccion_administrativa_id' => 5,
            'name' => 'SERVICIO DEPARTAMENTAL DE GESTIÓN SOCIAL (TGN)',
                'description' => '',
                'procedure_type_id' => 1,
                'class' => 'programa',
                'number' => '117',
                'programatic_category' => '42-0-020',
                'amount' => '2586705.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'direccion_administrativa_id' => 37,
                'name' => 'FOREST. ARBOLES DE CASTAÑA COM CAMP E INDIGENAS PROV VACA DIEZ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'proyecto',
                'number' => '121',
                'programatic_category' => '10-09080009200000-000',
                'amount' => '1952464.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'direccion_administrativa_id' => 55,
                'name' => 'MANTENIMIENTO Y REPOSICION DE REDES ELECTRIFICACION RURAL',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '11-0-080',
                'amount' => '1335042.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'direccion_administrativa_id' => 38,
                'name' => 'ARTICULACIÓN PISCÍCOLA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '12-0-060',
                'amount' => '300000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'direccion_administrativa_id' => 37,
                'name' => 'DESARROLLO AGROPECUARIO AMAZONICO',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '12-0-061',
                'amount' => '400000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'direccion_administrativa_id' => 61,
                'name' => 'APOYO INSTITUCIONAL AL DESAR PRODUCTIVO Y PROMOCION A LA ECONOMIA PLURAL',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '12-0-063',
                'amount' => '851940.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'direccion_administrativa_id' => 38,
                'name' => 'APOYO Y ASISTENCIA TECNICA DESARROLLO PESQUERO DPTO BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '12-0-082',
                'amount' => '350000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'direccion_administrativa_id' => 61,
                'name' => 'SERVICIO DEPARTAMENTAL DE RIEGO-BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '12-0-084',
                'amount' => '411588.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'direccion_administrativa_id' => 8,
                'name' => 'DESARROLLO INTEGRAL COMUNIDADES FRONTERIZAS DPTO. BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '12-0-085',
                'amount' => '367250.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'direccion_administrativa_id' => 6,
                'name' => 'FORTAL. AL DESAR. AGROPECUARIO DEL SECTOR CAMPESINO DPTO. BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '12-0-086',
                'amount' => '370000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'direccion_administrativa_id' => 61,
                'name' => 'programa DEL CACAO NATIVO AMAZONICO EN EL DPTO DEL BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '12-0-087',
                'amount' => '400000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'direccion_administrativa_id' => 61,
                'name' => 'APOYO A LAS COMUNIDADES INTERCULTURALES',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '12-0-088',
                'amount' => '185001.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'direccion_administrativa_id' => 6,
                'name' => 'APOYO PROD. SEMILLAS CERTIFICADAS COM. PROV. MARBAN',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'proyecto',
                'number' => '121',
                'programatic_category' => '12-09080018500000-000',
                'amount' => '366004.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'direccion_administrativa_id' => 6,
                'name' => 'APOYO PROD. E INDUST. YUCA PROV. YACUMA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'proyecto',
                'number' => '121',
                'programatic_category' => '12-09080018600000-000',
                'amount' => '1042544.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'direccion_administrativa_id' => 61,
                'name' => 'MEJ. GEN. GANADO VACUNO LECHERO S. CARLITOS PROV.MARBAN',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'proyecto',
                'number' => '121',
                'programatic_category' => '12-09080023300000-000',
                'amount' => '550000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'direccion_administrativa_id' => 61,
                'name' => 'CONTROL SANIDAD AGROP. E INOCUIDAD ALIMENTARIA DPTO DEL BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'proyecto',
                'number' => '121',
                'programatic_category' => '12-09080024200000-000',
                'amount' => '800000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'direccion_administrativa_id' => 61,
                'name' => 'PROMOCION AL TURISMO',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '13-0-070',
                'amount' => '1027056.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'direccion_administrativa_id' => 55,
                'name' => 'MANTENIMIENTO PREVENTIVO Y CORRECTIVO EDIFICIOS GAD-BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '14-0-080',
                'amount' => '1343883.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'direccion_administrativa_id' => 55,
                'name' => 'EQUIPAMIENTO MAESTRANZA OBRAS PÚBLICAS',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '14-0-081',
                'amount' => '930768.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'direccion_administrativa_id' => 55,
                'name' => 'MANTENIMIENTO REDES DE AGUA Y SANEAMIENTO BASICO Y AGUAS',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '15-0-060',
                'amount' => '1014316.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'direccion_administrativa_id' => 55,
                'name' => 'CONST. SISTEMAS DE AGUA POTABLE DPTO BENI ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'proyecto',
                'number' => '121',
                'programatic_category' => '15-09080019700000-000',
                'amount' => '1200000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'direccion_administrativa_id' => 15,
                'name' => 'APOYO OPERATIVO AL CONTROL. TRANSPARENCIA Y LUCHA CONTRA LA CORRUPCION',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-052',
                'amount' => '675000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'direccion_administrativa_id' => 66,
                'name' => 'APOYO AREA OPERATIVA AUDITORIA INTERNA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-053',
                'amount' => '1600001.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'direccion_administrativa_id' => 13,
                'name' => 'DESAR. PROG. FORTALECIMIENTO AL DESARROLLO ORGANIZACIONAL',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-054',
                'amount' => '560000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'direccion_administrativa_id' => 16,
                'name' => 'GESTION Y FORTALECIMIENTO DE RECURSOS HUMANOS',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-055',
                'amount' => '6015484.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'direccion_administrativa_id' => 9,
                'name' => 'FORTALECIMIENTO A LAS ORGANIZACIONES SOCIALES',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-059',
                'amount' => '245000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'direccion_administrativa_id' => 42,
                'name' => 'APOYO OPERATIVO DE LA SECRETARIA DPTAL. DE DESARROLLO HUMANO',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-060',
                'amount' => '2180000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'direccion_administrativa_id' => 13,
                'name' => 'ASISTENCIA INVERSION PUBLICA GAD BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-061',
                'amount' => '464850.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'direccion_administrativa_id' => 13,
                'name' => 'IMPLEMENTACION DEL SERVICIO DE LABORATORIO PARA ANALISIS  DE SUELOS EN EL DPTO DE BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-062',
                'amount' => '600000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'direccion_administrativa_id' => 13,
                'name' => 'RELACIONES INTERNACIONES',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-063',
                'amount' => '440000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'direccion_administrativa_id' => 9,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL EJECUTIVO DPTAL. ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-081',
                'amount' => '1625000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'direccion_administrativa_id' => 13,
                'name' => 'ELABORACION, SEGUIMIENTO Y EVALUACION DEL POA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-082',
                'amount' => '460531.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'direccion_administrativa_id' => 13,
                'name' => 'IMPLEM. SISTEMA SEGUIM. Y EVALUACION EJEC. PTDI. BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-083',
                'amount' => '500000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'direccion_administrativa_id' => 13,
                'name' => 'SEGUIMIENTO A LA IMPLEMENTACION DEL PLUS BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-085',
                'amount' => '950000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'direccion_administrativa_id' => 8,
                'name' => 'FORTALECIMIENTO A LA SECRETARIA GENERAL ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-087',
                'amount' => '1105000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'direccion_administrativa_id' => 59,
                'name' => 'FORTALECIMIENTO LEGISLATIVO ASAMBLEA DPTAL.',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-088',
                'amount' => '10159328.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'direccion_administrativa_id' => 10,
                'name' => 'FORTAL. SECRETARIA DE JUSTICIA PARA RESGUARDO DEL PATRIMONIO GAD-BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-090',
                'amount' => '306169.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'direccion_administrativa_id' => 10,
                'name' => 'IMPLEMENTACION GACETA OFICIAL DPTO AUTONOMO DEL BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-092',
                'amount' => '252293.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'direccion_administrativa_id' => 10,
                'name' => 'FORTAL. A LA CONST. DEL PROCESO AUTONÓMICO DPTO. BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-093',
                'amount' => '404185.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'direccion_administrativa_id' => 17,
                'name' => 'FORTAL. A LA GESTION PUBLICA DE LAS ENT. TERRITORIALES AUTONOMAS',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-094',
                'amount' => '640271.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'direccion_administrativa_id' => 9,
                'name' => 'IMPLEMENTACION DEL SISTEMA DE INTERACCION SOCIAL',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-095',
                'amount' => '2000000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'direccion_administrativa_id' => 13,
                'name' => 'APOYO OPERATIVO COMISION DE LIMITES POLITICOS ADM. BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-096',
                'amount' => '450000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'direccion_administrativa_id' => 42,
                'name' => 'FORTALECIMIENTO A DIVERSOS SECTORES DE LA JUVENTUD BENIANA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-098',
                'amount' => '255000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'direccion_administrativa_id' => 26,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL SUBGOB PROV BALLIVIAN',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-100',
                'amount' => '212648.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'direccion_administrativa_id' => 49,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO SAN BORJA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-102',
                'amount' => '190195.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'direccion_administrativa_id' => 47,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO SANTA ROSA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-103',
                'amount' => '190195.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'direccion_administrativa_id' => 23,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL SUB GOBE PROV. CERCADO',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-105',
                'amount' => '279177.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'direccion_administrativa_id' => 2,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO DE SAN JAVIER',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-107',
                'amount' => '223731.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'direccion_administrativa_id' => 25,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL SUB GOBE PROV. ITENEZ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-108',
                'amount' => '260000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'direccion_administrativa_id' => 20,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO DE MAGDALENA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-109',
                'amount' => '124773.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'direccion_administrativa_id' => 45,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO DE HUACARAJE',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-111',
                'amount' => '104773.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'direccion_administrativa_id' => 30,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO DE PUERTO SILES',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-115',
                'amount' => '95857.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'direccion_administrativa_id' => 22,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL SUB GOBE PROV. MARBAN',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-116',
                'amount' => '260000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'direccion_administrativa_id' => 28,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO DE LORETO',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-117',
                'amount' => '214518.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'direccion_administrativa_id' => 34,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO DE SAN ANDRES',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-118',
                'amount' => '221000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'direccion_administrativa_id' => 39,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL SUB GOBE PROV. MOJOS',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-119',
                'amount' => '273371.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'direccion_administrativa_id' => 31,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO DE MOXOS',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-120',
                'amount' => '137116.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'direccion_administrativa_id' => 19,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO DE GUAYARAMERIN',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-122',
                'amount' => '249202.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'direccion_administrativa_id' => 24,
                'name' => 'FORTALECIMIENTO INSTITUCIONAL CORREGIMIENTO DE SANTA ANA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-125',
                'amount' => '116245.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'direccion_administrativa_id' => 13,
                'name' => 'FORTAL. SECRETARIA DE PLANIFICACION Y DESARROLLO ECONOMICO',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '16-0-127',
                'amount' => '859619.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'direccion_administrativa_id' => 42,
                'name' => 'PROMOCION A LAS CULTURAS',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '23-0-080',
                'amount' => '600000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'direccion_administrativa_id' => 42,
                'name' => 'programa DE APOYO A LA EQUIDAD DE GENERO',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '25-0-021',
                'amount' => '560000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'direccion_administrativa_id' => 5,
            'name' => 'programa DE ATENCION NIÑO/NIÑA (PAN)',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '26-0-022',
                'amount' => '5054870.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'direccion_administrativa_id' => 36,
                'name' => 'ADMINISTRACION HOSPITAL PRESIDENTE GERMAN BUSCH RECPROP',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '40-0-017',
                'amount' => '5572758.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'direccion_administrativa_id' => 57,
                'name' => 'ADMINISTRACION HOSPITAL MATERNO INFANTIL BOLIVIANO- JAPONES RECPROP',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '40-0-018',
                'amount' => '2200000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'direccion_administrativa_id' => 53,
                'name' => 'BANCO DE SANGRE DE REFERENCIA DEPARTAMENTAL BENI RECPROP',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '40-0-019',
                'amount' => '1089009.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'direccion_administrativa_id' => 32,
                'name' => 'PLAN INTEGRAL DE SALUD',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '40-0-082',
                'amount' => '16000000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'direccion_administrativa_id' => 53,
                'name' => 'APOYO OPERATIVO BANCO DE SANGRE DE REFERENCIA DPTAL.',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '40-0-085',
                'amount' => '1000000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'direccion_administrativa_id' => 36,
                'name' => 'SERVICIOS Y PRODUCTOS DE SALUD UNIVERSAL Y GRATUITA - SUS',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '40-0-099',
                'amount' => '7930000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'direccion_administrativa_id' => 42,
                'name' => 'APOYO Y FORTALECIMIENTO A LA EDUCACION INTEGRAL DPTO BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '41-0-080',
                'amount' => '1005000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'direccion_administrativa_id' => 10,
                'name' => 'POTENCIAMIENTO DE LA  BIBLIOTECA AUTONÒMICA DPTO. BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '41-0-090',
                'amount' => '103972.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'direccion_administrativa_id' => 5,
                'name' => 'programa DE APOYO AL SEDEGES ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '42-0-070',
                'amount' => '4871780.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'direccion_administrativa_id' => 63,
                'name' => 'programa DE APOYO A LA PERSONA CON DISCAPACIDAD ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '42-0-095',
                'amount' => '1457128.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'direccion_administrativa_id' => 63,
                'name' => 'APOYO Y FORTALECIMIENTO AL CENTRO DE REHABILITACION CENDI-BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '42-0-096',
                'amount' => '359512.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'direccion_administrativa_id' => 63,
                'name' => 'PROG. APOYO REGISTRO UNICO NACIONAL PERSONA CON DISCAPACIDAD   ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '42-0-097',
                'amount' => '482563.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'direccion_administrativa_id' => 63,
                'name' => 'APOYO OPERATIVO COMITE DPTAL. DE PERSONA CON DISCAPACIDAD',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '42-0-098',
                'amount' => '619049.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'direccion_administrativa_id' => 26,
                'name' => 'MANTENIMIENTO RUTINARIO RED VIAL DPTAL PROV. BALLIVIAN  ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '43-0-080',
                'amount' => '326931.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'direccion_administrativa_id' => 23,
                'name' => 'MANTENIMIENTO RUTINARIO RED VIAL DPTAL PROV. CERCADO',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '43-0-081',
                'amount' => '1171014.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'direccion_administrativa_id' => 25,
                'name' => 'MANTENIMIENTO RUTINARIO RED VIAL DPTAL PROV. ITENEZ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '43-0-082',
                'amount' => '680796.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'direccion_administrativa_id' => 35,
                'name' => 'MANTENIMIENTO RUTINARIO RED VIAL DPTAL PROV. MAMORE',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '43-0-083',
                'amount' => '840826.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'direccion_administrativa_id' => 22,
                'name' => 'MANTENIMIENTO RUTINARIO RED VIAL DPTAL PROV. MARBAN',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '43-0-084',
                'amount' => '800000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'direccion_administrativa_id' => 39,
                'name' => 'MANTENIMIENTO RUTINARIO RED VIAL DPTAL PROV. MOJOS',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '43-0-085',
                'amount' => '475927.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'direccion_administrativa_id' => 40,
                'name' => 'MANTENIMIENTO RUTINARIO RED VIAL DPTAL PROV. VACA DIEZ ',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '43-0-086',
                'amount' => '558798.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'direccion_administrativa_id' => 24,
                'name' => 'MANTENIMIENTO RUTINARIO RED VIAL DPTAL PROV. YACUMA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '43-0-087',
                'amount' => '718046.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'direccion_administrativa_id' => 55,
                'name' => 'APOYO OPERATIVO DESARROLLO VIAL BENI',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '43-0-090',
                'amount' => '15100250.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'direccion_administrativa_id' => 48,
                'name' => 'PROMOCION AL DEPORTE',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '44-0-060',
                'amount' => '1783109.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'direccion_administrativa_id' => 68,
                'name' => 'APOYO OPERATIVO A LA SEGURIDAD CIUDADANA',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '95-0-070',
                'amount' => '400000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'direccion_administrativa_id' => 62,
                'name' => 'programa DE ALERTA TEMPRANA Y GESTION DE RIEGO',
                'description' => '',
                'procedure_type_id' => 5,
                'class' => 'programa',
                'number' => '121',
                'programatic_category' => '96-0-083',
                'amount' => '1900000.00',
                'year' => 2022,
                'start' => '2022-01-01',
                'finish' => '2022-12-31',
                'created_at' => '2022-01-10 16:00:00',
                'updated_at' => '2022-01-10 16:00:00',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}