<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UnidadesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('unidades')->delete();
        
        \DB::table('unidades')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nombre' => 'Unidad De Presupuesto',
                'sigla' => 'UP',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'nombre' => 'Seccion Caja',
                'sigla' => 'SC',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'nombre' => 'DIRECCION DPTAL. DE FINANZAS GAD - BENI',
                'sigla' => 'DDF',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'nombre' => 'Seccion de Prevision Social',
                'sigla' => 'SCE',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'nombre' => 'DIRECCIÓN DE PROGRAMACIÓN',
                'sigla' => 'DP',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'nombre' => 'DIRECCIÓN DPTAL. DE  RECURSOS HUMANOS GAD - BENI',
                'sigla' => 'DRRHH',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'nombre' => 'OTROS',
                'sigla' => 'O',
                'direccion_id' => 16,
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'nombre' => 'ORIGEN',
                'sigla' => 'OR',
                'direccion_id' => 16,
                'estado' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'nombre' => 'SECRETARIA DPTAL. DE ADMINISTRACION Y FINANZAS  GAD - BENI',
                'sigla' => 'SDAF',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'nombre' => 'Unidad De Tesoreria',
                'sigla' => 'UT',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'nombre' => 'Unidad De Contabilidad y Archivo',
                'sigla' => 'UCA',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'nombre' => 'DIRECCION DPTAL. ADMINISTRATIVA GAD - BENI',
                'sigla' => 'DADM',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'nombre' => 'DIRECCION DE BIODIVERSidAD',
                'sigla' => 'DB',
                'direccion_id' => 41,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'nombre' => 'DIRECCION DPTAL. DE RECAUDACIONES Y CONTROL DE INGRESOS PROPIOS GAD - BENI',
                'sigla' => 'DRCIP',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'nombre' => 'Unidad Juridica',
                'sigla' => 'UJ',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'nombre' => 'Seccion De Memoria Institucional',
                'sigla' => 'SMI',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'nombre' => 'DIRECCION DE AUDITORIA INTERNA',
                'sigla' => 'DAI',
                'direccion_id' => 9,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'nombre' => 'UNidAD DE SISTEMAS Y TELECOMUNICACIONES GAD - BENI',
                'sigla' => 'USIS',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'nombre' => 'DIRECCION DE INTERACCION SOCIAL',
                'sigla' => 'DIS',
                'direccion_id' => 9,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'nombre' => 'DESPACHO DE SECRETARIA DEPARTAMENTAL',
                'sigla' => 'DSD',
                'direccion_id' => 15,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'nombre' => 'Unidad De Registro y Control De Bienes Publicos',
                'sigla' => 'URCBP',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'nombre' => 'ADMINISTRATIVA',
                'sigla' => 'acg',
                'direccion_id' => 19,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'nombre' => 'Unidad De Mantenimiento y Reparacion',
                'sigla' => 'UMR',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'nombre' => 'DIRECCION DE OBRAS Y SERVICIOS BASICOS',
                'sigla' => 'DOSB',
                'direccion_id' => 55,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'nombre' => 'Unidad De Adquisición De Materiales y Suministros',
                'sigla' => 'UAMS',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 28,
                'nombre' => 'UNidAD JURidICA JUSTICIA',
                'sigla' => 'SJUJ',
                'direccion_id' => 10,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 29,
                'nombre' => 'DIRECCION SEGURidAD CIUDADANA',
                'sigla' => 'SGDSC',
                'direccion_id' => 8,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 30,
                'nombre' => 'DIRECCION DE GABINETE DESPACHO',
                'sigla' => 'DGD',
                'direccion_id' => 9,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 31,
                'nombre' => 'Unidad de Apoyo a Proyectos Agropecuarios',
                'sigla' => 'UAPA',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 32,
                'nombre' => 'Seccion de Recepcion y Despacho de Correspondencia',
                'sigla' => 'SRDC',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 33,
                'nombre' => ' Coordinacion de Organizaciones Sociales',
                'sigla' => 'COS',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 34,
                'nombre' => 'UNidAD DE DESARROLLO LEGISLATIVO',
                'sigla' => 'UDL',
                'direccion_id' => 10,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 35,
                'nombre' => 'Servicio Departamental Agropecuario del Beni',
                'sigla' => 'SEDAG',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 36,
                'nombre' => 'Secretaria de Desarrollo  Humano y Movilidad Social',
                'sigla' => 'SDHMS',
                'direccion_id' => 42,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 37,
                'nombre' => 'DIRECCION DE PROGRAMACION DE OPERACIONES',
                'sigla' => 'DPO',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 38,
            'nombre' => 'Servicio Departamental de Gestion Social (SEDEGES)',
                'sigla' => 'SDGS',
                'direccion_id' => 5,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 40,
                'nombre' => 'Unidad de Asistencia Social y Familia ',
                'sigla' => 'UASF',
                'direccion_id' => 5,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 41,
                'nombre' => 'Desarrollo del Tipnis',
                'sigla' => 'DdT',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 42,
                'nombre' => 'Dirección de Autonomía y Desarrollo Institucional ',
                'sigla' => 'DADI',
                'direccion_id' => 10,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 43,
                'nombre' => 'Dirección de coordinación de Justicia y Derechos Ciudadanos',
                'sigla' => 'DCJDC',
                'direccion_id' => 10,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 44,
                'nombre' => 'Seccion de Seguridad Alimentaria  COE',
                'sigla' => 'SSA',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 45,
                'nombre' => 'Sección de Almacenes COE',
                'sigla' => 'SACOE',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 46,
                'nombre' => 'Unidad Administración y Finanzas SEDEDE',
                'sigla' => 'UADM',
                'direccion_id' => 48,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 47,
                'nombre' => 'Direccion de Coordinacion con Movimientos Sociales',
                'sigla' => 'DCMS',
                'direccion_id' => 9,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 48,
                'nombre' => 'DIRECCIÓN DPTAL. DE BIENESTAR LABORAL Y PREVISIÓN SOCIAL GAD - BENI',
                'sigla' => 'DBLPS',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 50,
            'nombre' => 'Alerta Temprana (COE)',
                'sigla' => 'ATCOE',
                'direccion_id' => 8,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 51,
                'nombre' => 'Direccion de Comercio Industria y Servicios',
                'sigla' => 'DCIS',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 52,
                'nombre' => 'Direccion de Sistema de Alerta Temprana y Riesgo',
                'sigla' => 'DSATR',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 54,
                'nombre' => 'Unidad Administrativa  SDAF',
                'sigla' => 'UADM',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 55,
                'nombre' => 'Direccion de Fortalecimiento Municipal',
                'sigla' => 'DFM',
                'direccion_id' => 17,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 56,
                'nombre' => 'Dirección de Desarrollo Ganadero',
                'sigla' => 'DDG',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 57,
                'nombre' => 'Dirección de Turismo',
                'sigla' => 'DT',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 58,
                'nombre' => 'Dirección de Desarrollo Indigena',
                'sigla' => 'DDI',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 59,
                'nombre' => 'Dirección de Desarrollo Productivo Campesino',
                'sigla' => 'DDPC',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 60,
                'nombre' => 'Dirección de Desarrollo de Comunidades Interculturales',
                'sigla' => 'DDCI',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 61,
                'nombre' => 'Dirección de Desarrollo Agricola',
                'sigla' => 'DDA',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 65,
                'nombre' => 'Dirección Administrativa de Desarrollo Productivo y Economía Plural',
                'sigla' => 'DADPE',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 66,
                'nombre' => 'Unidad de Sistemas informaticos',
                'sigla' => 'USI',
                'direccion_id' => 36,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 67,
            'nombre' => 'Unidad de Administracion y Finanzas (COE)',
                'sigla' => 'UADMF',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 68,
                'nombre' => 'Seccion de Gestion de Riesgos COE',
                'sigla' => 'SGR',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 69,
                'nombre' => 'Seccion de Respuesta Inmediata COE',
                'sigla' => 'SRI',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 70,
                'nombre' => 'Seccion de Alerta Temprana COE',
                'sigla' => 'SAT',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 71,
                'nombre' => 'Seccion de Mantenimiento e Infraestructura COE',
                'sigla' => 'SMI',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 72,
                'nombre' => 'Seccion Hidraulica COE',
                'sigla' => 'SH',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 73,
                'nombre' => 'Seccion de Recursos Humanos COE',
                'sigla' => 'SRRHH',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 74,
                'nombre' => 'Seccion de Activos Fijos COE',
                'sigla' => 'SAF',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 75,
                'nombre' => 'Seccion de Bienes y Servicios COE',
                'sigla' => 'SBS',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 76,
                'nombre' => 'Seccion de Tesoreria COE',
                'sigla' => 'ST',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 77,
                'nombre' => 'Despacho Sub Gobernacion ',
                'sigla' => 'DSGM',
                'direccion_id' => 22,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 78,
                'nombre' => 'Seccion de Presupuesto',
                'sigla' => 'SDP',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 79,
                'nombre' => 'Seccion ppto Y Contabilidad',
                'sigla' => 'SPC',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 80,
                'nombre' => 'Seccion de Asesoria Legal',
                'sigla' => 'SAL',
                'direccion_id' => 62,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 81,
                'nombre' => 'Despacho de Secretaria General',
                'sigla' => 'DSG',
                'direccion_id' => 8,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 82,
                'nombre' => 'Direccion Departamental de Frontera Guayaramerin',
                'sigla' => 'DDF',
                'direccion_id' => 50,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 83,
                'nombre' => 'Despacho de Secretaria de Justicia',
                'sigla' => 'DSJ',
                'direccion_id' => 10,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 84,
                'nombre' => 'Despacho de Corregimiento de Municipio Reyes',
                'sigla' => 'DCMR',
                'direccion_id' => 44,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 85,
                'nombre' => 'Despacho de Corregimiento del Municipio de Riberalta',
                'sigla' => 'DCMR',
                'direccion_id' => 46,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 86,
                'nombre' => 'Direccion Dptal. del Seguro Universal de Salud GAD-BENI',
                'sigla' => 'DPSUS',
                'direccion_id' => 27,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 87,
                'nombre' => 'Direccion de Administracion y Finanzas',
                'sigla' => 'DADMF',
                'direccion_id' => 55,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 88,
                'nombre' => 'Direccion Juridica - SDOP',
                'sigla' => 'DJSOP',
                'direccion_id' => 55,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 89,
                'nombre' => 'Dirección de desarrollo vial y transporte',
                'sigla' => 'DDVT',
                'direccion_id' => 55,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 90,
                'nombre' => 'Despacho de Corregimiento Rurrenabaque',
                'sigla' => 'DCMR',
                'direccion_id' => 43,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 91,
                'nombre' => 'Despacho de Sub Gobernacion Ballivian',
                'sigla' => 'DSBPB',
                'direccion_id' => 26,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 92,
                'nombre' => 'Despacho Corregimiento Santa Rosa',
                'sigla' => 'DCSR',
                'direccion_id' => 47,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 93,
                'nombre' => 'Despacho de Corregimiento Loreto',
                'sigla' => 'DCML',
                'direccion_id' => 28,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 94,
                'nombre' => 'Despacho de Corregimiento de San Borja',
                'sigla' => 'DCSB',
                'direccion_id' => 49,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 95,
                'nombre' => 'Despacho de Sub Gobernación Itenez',
                'sigla' => 'DSGI',
                'direccion_id' => 25,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 96,
                'nombre' => 'Despacho Sub Gobernacion Cercado',
                'sigla' => 'DSGC',
                'direccion_id' => 23,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 97,
                'nombre' => 'Despacho Sub Gobernacion Yacuma',
                'sigla' => 'DSGY',
                'direccion_id' => 24,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 98,
                'nombre' => 'Despacho Sub Gobernacion Moxos',
                'sigla' => 'DSGM',
                'direccion_id' => 39,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 99,
                'nombre' => 'Despacho Sub Gobernacion Mamore',
                'sigla' => 'DSGM',
                'direccion_id' => 35,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 100,
                'nombre' => 'Despacho Sub Gobernacion Vaca Diez',
                'sigla' => 'DSGVD',
                'direccion_id' => 40,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 101,
                'nombre' => 'Despacho Corregimiento Trinidad',
                'sigla' => 'DCT',
                'direccion_id' => 1,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 102,
                'nombre' => 'Despacho de Corregimiento del Municipio San Ignacio',
                'sigla' => 'DCMSI',
                'direccion_id' => 31,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 103,
                'nombre' => 'Unidad Administrativa SDJ',
                'sigla' => 'UADM',
                'direccion_id' => 10,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 104,
                'nombre' => 'Unidad de Servicio Departamental de Riego',
                'sigla' => 'USDR',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 105,
                'nombre' => 'Unidad de Planificación e Infraestructura SEDEDE',
                'sigla' => 'UI',
                'direccion_id' => 48,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 106,
                'nombre' => 'Unidad Administrativa',
                'sigla' => 'UA',
                'direccion_id' => 53,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 107,
                'nombre' => 'Despacho de Corregimiento del Municipio de San Ramon',
                'sigla' => 'DCMSR',
                'direccion_id' => 3,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 108,
                'nombre' => 'DIRECCION DE CODEPEDIS - BENI',
                'sigla' => 'DCO',
                'direccion_id' => 63,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 109,
                'nombre' => 'Despacho de Secretaria Departamental Des. Amazonico',
                'sigla' => 'DSDDA',
                'direccion_id' => 37,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 110,
                'nombre' => 'Despacho de Secretaria Departamental Obras Publicas',
                'sigla' => 'DSDOP',
                'direccion_id' => 55,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 111,
                'nombre' => 'UNASVI',
                'sigla' => 'UUOP',
                'direccion_id' => 55,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 112,
                'nombre' => 'Dirección Departamental de Planificación Estratégica',
                'sigla' => 'DDPE',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 113,
                'nombre' => 'Dirección Departamental de Proyecto Estratégico y Concurrentes',
                'sigla' => 'DDPEC',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 114,
                'nombre' => 'Dirección Departamental de Comercio, Industria y Servicio',
                'sigla' => 'DDCIS',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 115,
                'nombre' => 'Dirección Departamental de Desarrollo Organizacional',
                'sigla' => 'DDDO',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 116,
                'nombre' => 'Dirección Departamental de Inversión Publica ',
                'sigla' => 'DDIP',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 117,
                'nombre' => 'Dirección Departamental de Programación del Operaciones',
                'sigla' => 'DDPO',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 118,
                'nombre' => 'Dirección Departamental de Ordenamiento Territorial y Limites',
                'sigla' => 'DDOTL',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 119,
                'nombre' => 'Despacho de Secretaria Departamental Planificacion  y Desarrollo Economico',
                'sigla' => 'DSDDE',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 120,
                'nombre' => 'Despacho de Corregimiento Municipio Huacaraje',
                'sigla' => 'DCMH',
                'direccion_id' => 45,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 121,
                'nombre' => 'Direccion del SEDES',
                'sigla' => 'DS',
                'direccion_id' => 32,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 122,
                'nombre' => 'Despacho Corregimiento Exaltacion',
                'sigla' => 'DCEX',
                'direccion_id' => 29,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 123,
                'nombre' => 'Despacho de Corregimiento Magdalena',
                'sigla' => 'DCM',
                'direccion_id' => 20,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 124,
                'nombre' => 'Despacho de Corregimiento Municipio San Javier',
                'sigla' => 'DCMSJ',
                'direccion_id' => 2,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 125,
                'nombre' => 'SUSA VACA DIEZ',
                'sigla' => 'SUSAV',
                'direccion_id' => 18,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 126,
                'nombre' => 'Despacho Corregimiento Baures',
                'sigla' => 'DCBA',
                'direccion_id' => 21,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 127,
                'nombre' => 'Undidad de Bienes y Servicio HMI',
                'sigla' => 'UBSHM',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 128,
                'nombre' => 'Unidad de Contabilidad HMI',
                'sigla' => 'UCHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 129,
                'nombre' => 'Unidad de Presupuesto HMI',
                'sigla' => 'UPHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 130,
                'nombre' => 'Unidad de Tesoreria HMI',
                'sigla' => 'UTHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 131,
                'nombre' => 'Unidad de Programacion y Operaciones HMI',
                'sigla' => 'UPOHM',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 132,
                'nombre' => 'Seccion de Caja HMI',
                'sigla' => 'SCHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 133,
                'nombre' => 'Unidad de Administracion HMI',
                'sigla' => 'UAMD',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 134,
                'nombre' => 'Seccion de Facturacion HMI',
                'sigla' => 'SFHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 135,
                'nombre' => 'Seccion de Farmacia HMI',
                'sigla' => 'SFHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 136,
                'nombre' => 'Seccion de Matenimiento HMI',
                'sigla' => 'SMHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 137,
                'nombre' => 'Seccion de Limpieza HMI',
                'sigla' => 'SLHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 138,
                'nombre' => 'Seccion de Almacenes HMI',
                'sigla' => 'SAHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 139,
                'nombre' => 'Unidad de Recursos Humanos HMI',
                'sigla' => 'URRHH',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 140,
                'nombre' => 'Direccion de Hospital Materno Infantil ',
                'sigla' => 'DHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 141,
                'nombre' => 'Seccion de Ecografia HMI',
                'sigla' => 'SEHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 142,
                'nombre' => 'Seccion de Rayos X  HMI',
                'sigla' => 'SRXHM',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 143,
                'nombre' => 'Unidad de Estadistica HMI',
                'sigla' => 'UEHMI',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 144,
                'nombre' => 'Seccion de Servicio de Laboratoria HMI',
                'sigla' => 'SSLHM',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 145,
                'nombre' => 'Direccion General Hospital German Busch',
                'sigla' => 'DGHGB',
                'direccion_id' => 36,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 146,
                'nombre' => 'Despacho de Corregimiento Municipio Santa Ana',
                'sigla' => 'DCMSA',
                'direccion_id' => 33,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 147,
                'nombre' => 'Despacho Corregiminetos San Andres',
                'sigla' => 'DCSA',
                'direccion_id' => 34,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 148,
                'nombre' => 'Despacho Corregimineto puerto siles',
                'sigla' => 'DCPS',
                'direccion_id' => 30,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 149,
                'nombre' => 'Despacho Corregimineto Municipio San Joaquin',
                'sigla' => 'DCMSJ',
                'direccion_id' => 4,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 150,
                'nombre' => 'DIRECCIÓN  DPTAL.  DE MINERÍA GAD - BENI',
                'sigla' => 'DDMIN',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 151,
                'nombre' => 'Unidad Ventanilla Única de Tramites y Recaudaciones',
                'sigla' => 'UVUTR',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 152,
                'nombre' => 'Unidad de Electrificación Rural - SDOP',
                'sigla' => 'UER',
                'direccion_id' => 55,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 153,
                'nombre' => 'Unidad de Desarrollo  Sistemas Informaticos',
                'sigla' => 'UDSI',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 154,
                'nombre' => 'Gabinete SDAF',
                'sigla' => 'GSDAF',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            146 => 
            array (
                'id' => 155,
                'nombre' => 'Unidad de Seguridad Alimentaria y Nutrición Familiar',
                'sigla' => 'USANF',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            147 => 
            array (
                'id' => 156,
                'nombre' => 'Dirección Departamental Indigena',
                'sigla' => 'DDI',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            148 => 
            array (
                'id' => 157,
                'nombre' => 'Unidad Transporte Fluvial',
                'sigla' => 'UTF',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            149 => 
            array (
                'id' => 158,
                'nombre' => 'Unidad Gestión Territorial',
                'sigla' => 'UGT',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            150 => 
            array (
                'id' => 159,
                'nombre' => 'Sedes',
                'sigla' => 'SEDES',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            151 => 
            array (
                'id' => 160,
                'nombre' => 'Direccion Desarrollo Campesino',
                'sigla' => 'DDC',
                'direccion_id' => 6,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            152 => 
            array (
                'id' => 161,
                'nombre' => 'Direccion Del TIPNIS',
                'sigla' => 'DT',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            153 => 
            array (
                'id' => 162,
                'nombre' => 'DIRECCION DE GESTION TERRITORIAL',
                'sigla' => 'DDGT',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            154 => 
            array (
                'id' => 163,
                'nombre' => 'Unidad de Fortalecimiento a Procesos Organizacional',
                'sigla' => 'UFPO',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            155 => 
            array (
                'id' => 164,
                'nombre' => 'Unidad de Desarrollo Agropecuario ',
                'sigla' => 'UDA',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            156 => 
            array (
                'id' => 165,
                'nombre' => 'Unidad de Culturas y Lenguas Originarias',
                'sigla' => 'UCLO',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            157 => 
            array (
                'id' => 166,
                'nombre' => 'Unidad de Manejo Flora y Fauna',
                'sigla' => 'UMFF',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            158 => 
            array (
                'id' => 167,
                'nombre' => 'Unidad de Soberania y Seguridad Alimentaria',
                'sigla' => 'USSA',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            159 => 
            array (
                'id' => 168,
                'nombre' => 'DIRECCION DE MANEJO Y DESARROLLO AGROSILVOPASTORIL',
                'sigla' => 'DDMDA',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            160 => 
            array (
                'id' => 169,
                'nombre' => 'Unidad de Asesoría Jurídica',
                'sigla' => 'UAJ',
                'direccion_id' => 64,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            161 => 
            array (
                'id' => 170,
                'nombre' => 'Uniplus',
                'sigla' => 'UPLS',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            162 => 
            array (
                'id' => 171,
                'nombre' => 'Direccion Interaccion Social',
                'sigla' => 'DIS',
                'direccion_id' => 65,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            163 => 
            array (
                'id' => 172,
                'nombre' => 'Dirección Auditoria Interna',
                'sigla' => 'DAI',
                'direccion_id' => 66,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            164 => 
            array (
                'id' => 173,
                'nombre' => 'Direccion Coordinación Movimientos Sociales',
                'sigla' => 'DCMS',
                'direccion_id' => 67,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            165 => 
            array (
                'id' => 174,
                'nombre' => 'Dirección Seguridad Ciudadana GAD',
                'sigla' => 'DSC',
                'direccion_id' => 68,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            166 => 
            array (
                'id' => 176,
                'nombre' => 'Direccion Dptal. Relacionamiento Internacional',
                'sigla' => 'DDRI',
                'direccion_id' => 13,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            167 => 
            array (
                'id' => 178,
                'nombre' => 'Gabinete SDMEyH',
                'sigla' => 'GSDME',
                'direccion_id' => 69,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            168 => 
            array (
                'id' => 179,
                'nombre' => 'Dirección Dptal. de Energía e Hidrocarburos',
                'sigla' => 'DDEH',
                'direccion_id' => 69,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            169 => 
            array (
                'id' => 180,
                'nombre' => 'Direccion Dptal. de Mineria',
                'sigla' => 'DDM',
                'direccion_id' => 69,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            170 => 
            array (
                'id' => 181,
                'nombre' => 'Dirección Re activación Económica',
                'sigla' => 'DRE',
                'direccion_id' => 61,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            171 => 
            array (
                'id' => 182,
                'nombre' => 'Unidad de Asesoría legal',
                'sigla' => 'UAL',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            172 => 
            array (
                'id' => 183,
                'nombre' => 'Unidad de Sistemas',
                'sigla' => 'UDS',
                'direccion_id' => 57,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            173 => 
            array (
                'id' => 184,
                'nombre' => 'Dirección del Sedede',
                'sigla' => 'DDS',
                'direccion_id' => 48,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            174 => 
            array (
                'id' => 185,
                'nombre' => 'Unidad Jurídica SEDEDE',
                'sigla' => 'UJS',
                'direccion_id' => 48,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            175 => 
            array (
                'id' => 186,
                'nombre' => 'Unidad de Desarrollo de Deporte SEDEDE',
                'sigla' => 'UDDS',
                'direccion_id' => 48,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            176 => 
            array (
                'id' => 187,
                'nombre' => 'Unidad de Administración y Finanzas',
                'sigla' => 'UAF',
                'direccion_id' => 5,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            177 => 
            array (
                'id' => 189,
                'nombre' => 'Unidad de Género, Generacionales y Servicios Sociales',
                'sigla' => 'UGGSS',
                'direccion_id' => 5,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            178 => 
            array (
                'id' => 190,
                'nombre' => 'Unidad de Asuntos Jurídicos',
                'sigla' => 'UAJ',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            179 => 
            array (
                'id' => 191,
                'nombre' => 'Unidad de Coordinación, Acreditación y Control de Centros',
                'sigla' => 'UCACC',
                'direccion_id' => 5,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            180 => 
            array (
                'id' => 192,
                'nombre' => 'Unidad de Contrataciones Bienes y Servicio',
                'sigla' => 'UCNS',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            181 => 
            array (
                'id' => 193,
                'nombre' => 'UNIDAD DE RECEPCION DE DOCUMENTOS EXTERNOS',
                'sigla' => 'RDE',
                'direccion_id' => 16,
                'estado' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
    }
}