@extends('layouts.template-print-legal')

@section('page_title', 'Contrato Personal Eventual')

@php
    $months = array('', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
    $code = $contract->code;
    $signature = $contract->signature;
    $sueldo = $contract->cargo->nivel->where('IdPlanilla', $contract->cargo->idPlanilla)->first()->Sueldo;

    // Calcular finalización de contrato en caso de tener adenda
    if($contract->addendums->count() > 0) {
        $contract_finish = date('Y-m-d', strtotime($contract->addendums->first()->start." -1 days"));
    } else {
        $contract_finish = $contract->finish;
    }
@endphp

@section('qr_code')
    <div id="qr_code" >
        @php
            $qrcode = QrCode::size(70)->generate('CONTRATO DE PRESTACIÓN DE SERVICIOS PARA PERSONAL EVENTUAL GAD-BENI-C.E- '.$code.' '.$contract->person->first_name.' '.$contract->person->last_name.' con C.I. '.$contract->person->ci.', del '.date('d', strtotime($contract->start)).' de '.$months[intval(date('m', strtotime($contract->start)))].' al '.date('d', strtotime($contract_finish)).' de '.$months[intval(date('m', strtotime($contract_finish)))].' de '.date('Y', strtotime($contract_finish)).' con un sueldo de '.number_format($sueldo, 2, ',', '.').' Bs.');
        @endphp
        {!! $qrcode !!}
    </div>
@endsection

@section('content')
    @if ($contract->files->count() > 0)
        <div class="content">
            {!! $contract->files[0]->text !!}
        </div>
    @else
        <div class="content" style="text-align: justify">
            <h2 class="text-center" style="font-size: 18px">CONTRATO DE PRESTACI&Oacute;N DE SERVICIOS PARA PERSONAL EVENTUAL <br> <small>GAD-BENI-C.E-{{ $code }}</small></h2>
            <p><span>Conste por el presente Contrato Administrativo de Personal Eventual, que celebra por una parte el Servicio Departamental de Gesti&oacute;n Social <strong>(SEDEGES &ndash; Beni)</strong>, con <strong>NIT N&ordm; {{ $contract->direccion_administrativa->nit ?? '177396029' }}</strong>, con domicilio ubicado en {{ $contract->direccion_administrativa->direccion ?? 'el edificio de Gobernación en Acera Sud de la Plaza Mariscal José Ballivián' }}, en la Ciudad/Localidad de {{ $contract->direccion_administrativa->city->name ?? 'la SANTISIMA TRINIDAD' }}, Provincia {{ $contract->direccion_administrativa->city->province ?? 'CERCADO' }} del Departamento del BENI, representado legalmente por la/el <strong>{{ $signature ? $signature->name : setting('firma-autorizada.name') }}</strong>, con Cedula de Identidad <strong>N&ordm; {{ $signature ? $signature->ci : setting('firma-autorizada.ci') }}</strong>, en su <span style="color: black; mso-themecolor: text1;">condici&oacute;n</span> de <strong>{{ $signature ? $signature->job : setting('firma-autorizada.job') }}</strong> designada mediante {{ $signature ? $signature->designation_type : 'Resolución de Gobernación' }} N&ordm; {{ $signature ? $signature->designation : setting('firma-autorizada.designation') }}, de fecha {{ $signature ? $signature->designation_date ? date('d', strtotime($signature->designation_date)).' de '.$months[intval(date('m', strtotime($signature->designation_date)))].' de '.date('Y', strtotime($signature->designation_date)) : setting('firma-autorizada.designation-date') : setting('firma-autorizada.designation-date') }}; que en adelante se denominar&aacute; simplemente como <strong>SEDEGES &ndash; Beni</strong>; y por otra parte {{ $contract->person->gender == 'masculino' ? 'el señor' : 'la señora' }} <b>{{ $contract->person->first_name }} {{ $contract->person->last_name }} </b>mayor de edad, h&aacute;bil por derecho, titular de la <span style="color: black; mso-themecolor: text1;">C&eacute;dula </span>de Identidad <strong>N&ordm; {{ $contract->person->ci }}</strong>, en adelante para efectos del presente Contrato denominado simplemente {!! $contract->person->gender == 'masculino' ? 'el <b>CONTRATADO</b>' : 'la <b>CONTRATADA</b>' !!}, quienes celebran y suscriben el presente Contrato Administrativo al tenor de las siguientes Cl&aacute;usulas:</span></p>
            <p><strong><span>CL&Aacute;USULA PRIMERA. - (ANTECEDENTES):</span></strong></p>
            <p><span>A requerimiento de las diferentes Unidades (Jefaturas, &Aacute;reas, Secciones y Centros) del Servicio Departamental de Gesti&oacute;n Social (<strong>SEDEGES &ndash; Beni)</strong>, el &Aacute;rea de Recursos Humanos da inicio a los procesos de reclutamiento y selecci&oacute;n de Personal Eventual. En este sentido, el &Aacute;rea de Recursos Humanos, ha evaluado el perfil profesional al Postulante y ha realizado la revisi&oacute;n documental del Curriculum Vitae presentado <strong>(t&iacute;tulos y certificados)</strong> por <strong>{{ $contract->person->gender == 'masculino' ? 'el' : 'la' }} postulante,</strong> recomendando al Director (a) del Servicio Departamental de Gesti&oacute;n Social &nbsp;(<strong>SEDEGES &ndash; Beni)</strong>, su contrataci&oacute;n, y elaboraci&oacute;n del Contrato, tomando en cuenta que re&uacute;ne y cumple con el est&aacute;ndar de los requisitos exigidos para el cargo.</span></p>
            <p><span>Que la Certificaci&oacute;n Presupuestaria emitida por el <strong>JEFE DE LA UNIDAD DE ADMINISTRACION Y FINANZAS</strong> indica que existen los recursos econ&oacute;micos suficientes para efectuar la presente contrataci&oacute;n del Personal Eventual, del Servicio Departamental de Gesti&oacute;n Social del Beni <strong>(SEDEGES &ndash; Beni).</strong></span></p>
            <p><span>Por lo se&ntilde;alado la/el Director (a) del Servicio Departamental de Gesti&oacute;n Social &nbsp;<strong>SEDEGES - Beni</strong>, en atenci&oacute;n a dicha recomendaci&oacute;n y Certificaci&oacute;n Presupuestaria, instruye al &Aacute;rea de Recursos Humanos la elaboraci&oacute;n del proceso de Contrataci&oacute;n y a la Unidad Jur&iacute;dica la elaboraci&oacute;n del Contrato, correspondiente.</span></p>
            <p><strong><span>CL&Aacute;USULA SEGUNDA. - (LEGISLACION APLICABLE): </span></strong></p>
            <p><span>El presente Contrato se celebra al amparo de las siguientes disposiciones:</span></p>
            <p style="margin-left: 36.0pt;"><span>La Constituci&oacute;n Pol&iacute;tica del Estado</span></p>
            <p style="margin-left: 36.0pt;"><span>Ley de Administraci&oacute;n y Control Gubernamental N&ordm; 1178, de 20 de julio de 1990 </span></p>
            <p style="margin-left: 36.0pt;"><span>Ley de Presupuesto de General del Estado N&ordm; 1493, de 17 de diciembre del 2022</span></p>
            <p style="margin-left: 36.0pt;"><span>Decreto Supremo N&ordm; 4848, de fecha 28 de diciembre del 2022 &ldquo;Reglamento a la Ley 1493&rdquo;</span></p>
            <p style="margin-left: 36.0pt;"><span>Ley Marco de Autonom&iacute;a y Descentralizaci&oacute;n &ldquo;Andr&eacute;s Ib&aacute;&ntilde;ez&rdquo;, de fecha 19 de julio de 2010</span></p>
            <p style="margin-left: 36.0pt;"><span>Ley Contra el Racismo y toda forma de Discriminaci&oacute;n N&ordm; 045, de 08 de octubre de 2010</span></p>
            <p style="margin-left: 36.0pt;"><span>Ley de Lucha contra la Corrupci&oacute;n Enriquecimiento Il&iacute;cito e Investigaci&oacute;n de Fortunas &ldquo;Marcelo Quiroga Santa Cruz&rdquo; N&ordm; 004, de 31 de marzo de 2010.</span></p>
            <p style="margin-left: 36.0pt;"><span>Ley de Pensiones N&ordm; 65, de fecha 10 de diciembre de 2010</span></p>
            <p style="margin-left: 36.0pt;"><span>C&oacute;digo de Seguridad Social, de 14 de diciembre de 1956.</span></p>
            <p style="margin-left: 36.0pt;"><span>Decreto Supremo 23318-A, de 3 de noviembre de 1992, que aprueba el Reglamento de la Responsabilidad por la Funci&oacute;n P&uacute;blica y su Decreto Supremo, modificatorio.</span></p>
            <p class="MsoNoSpacing"><strong><span>CL&Aacute;USULA TERCERA. - (DOCUMENTOS INTEGRANTES DEL CONTRATO):</span></strong></p>
            <p class="MsoNoSpacing"><span>Forman parte del presente Contrato los siguientes documentos:</span></p>
            <p style="margin-left: 35.45pt;"><span>Requisitos m&iacute;nimos elaborados por la Unidad Solicitante (Misi&oacute;n Espec&iacute;fica)</span></p>
            <p style="margin-left: 35.45pt;"><span>Certificaci&oacute;n Presupuestaria.</span></p>
            <p style="margin-left: 35.45pt;"><span>Carta de Invitaci&oacute;n.</span></p>
            <p style="margin-left: 35.45pt;"><span>Curriculum Vitae.</span></p>
            <p><strong><span>CL&Aacute;SULA&nbsp; CUARTA. - (DEL OBJETO DEL CONTRATO):</span></strong></p>
            <p><span>El objeto del presente Contrato es establecer los t&eacute;rminos, condiciones, y sobre todo los <span style="color: black;">derechos y obligaciones</span>, bajo los cuales el <strong>SEDEGES - Beni</strong> contrata los servicios de forma eventual de <b>{{ $contract->person->first_name }} {{ $contract->person->last_name }}</b>, para que este en m&eacute;rito a su formaci&oacute;n y experiencia profesional u ocupaci&oacute;n, desempe&ntilde;e funciones como <strong>{{ Str::upper($contract->cargo->Descripcion) }}</strong>, de el/la <b>{{ Str::upper($contract->unidad_administrativa->nombre) }}</b> de conformidad con el perfil del cargo y Misi&oacute;n Espec&iacute;fica establecidos para este efecto y que forman parte del presente Contrato.</span></p>
            <p><strong><span>CL&Aacute;USULA QUINTA. - (REMUNERACI&Oacute;N). </span></strong></p>
            @php
                $numeros_a_letras = new NumeroALetras();
            @endphp
            <p><span>Por las funciones a ser cumplidas durante la vigencia del presente Contrato, a<strong>l (a) CONTRATADO (A)</strong> se le asignar&aacute; el nivel <strong>{{ $contract->cargo->nivel->where('IdPlanilla', $contract->cargo->idPlanilla)->first()->NumNivel }}</strong>de nuestra Escala Salarial de Personal Eventual, vigente, percibiendo una remuneraci&oacute;n mensual de <strong>Bs. {{ number_format($sueldo, 2, ',', '.') }} ({{ $numeros_a_letras->toInvoice(number_format($sueldo, 2, '.', ''), 2, 'Bolivianos') }})</strong>. Fuera de la remuneraci&oacute;n acordada, <strong>no habr&aacute; lugar al pago de ning&uacute;n incremento u otro beneficio social adicional</strong>, conforme se tiene anotado en su Cl&aacute;usula Cuarta del presente Contrato.</span></p>
            
            <p><strong><span>CL&Aacute;USULA SEXTA. - (PLAZO Y VIGENCIA DE PRESTACI&Oacute;N DEL SERVICIO):</span></strong></p>
            <p><strong><span>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</span></strong><span> prestar&aacute; los servicios de forma eventual, comput&aacute;ndose la vigencia y el plazo a partir del d&iacute;a de la suscripci&oacute;n del presente Contrato hasta el <strong>{{ date('d', strtotime($contract_finish)) }} de {{ $months[intval(date('m', strtotime($contract_finish)))] }} de {{ date('Y', strtotime($contract_finish)) }}</strong>, dejando en claro qu&eacute;, debido a la naturaleza administrativa y la eventualidad del servicio, no se aplicara la t&aacute;cita reconducci&oacute;n del Contrato al vencimiento del mismo, no siendo necesario la &nbsp;notificaci&oacute;n de culminaci&oacute;n del Contrato.</span></p>
            
            <p><strong><span>CL&Aacute;USULA S&Eacute;PTIMA. - (NATURALEZA DEL CONTRATO): </span></strong></p>
            <p><span>El presente Contrato es de car&aacute;cter administrativo ya que interviene como una de las partes la entidad p&uacute;blica del Servicio Departamental de Gesti&oacute;n Social <strong>SEDEGES &ndash; Beni</strong>, cuyo marco normativo se cimienta en un proceso de contrataci&oacute;n de Personal regido por el art&iacute;culo 6&ordm; de la Ley 2027;&nbsp; el Art. 5&deg; del D.S. N&ordm; 27375, con relaci&oacute;n al art&iacute;culo 18 p&aacute;rrafo II inciso e) numeral 5), referido a las Normas B&aacute;sicas del Sistema de Administraci&oacute;n de Personal, por lo que el presente Contrato es un Contrato Administrativo; consiguientemente, no est&aacute; obligado a reconocer beneficios sociales u otros derechos (vacaci&oacute;n, bono de antig&uuml;edad) que emanen de la Ley General del Trabajo y otras disposiciones conexas.</span></p>
            
            <p><span>Asimismo, el presente contrato est&aacute; inmerso dentro de las previsiones contenidas en la Ley N&ordm; 1178, de 20 de julio de 1990, de Administraci&oacute;n y Control Gubernamentales y dem&aacute;s normas conexas.</span></p>
            <p><strong><span>CL&Aacute;USULA OCTAVA. - (LUGAR DE PRESTACI&Oacute;N DE LOS SERVICIOS Y HORARIOS). </span></strong></p>
            <p><strong><span>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }} </span></strong><span>prestar&aacute; sus servicios en las instalaciones de los ambientes u oficinas que se hallan bajo administraci&oacute;n del Servicio Departamental de Gesti&oacute;n Social del &nbsp;<strong>SEDEGES-Beni</strong>, de acuerdo a la naturaleza de las funciones y horarios establecidos por el SEDEGES Beni.</span></p>
            
            <p style="margin-left: 21.3pt; text-indent: -21.3pt;"><strong><span>CL&Aacute;USULA NOVENA. - (DERECHOS Y DEBERES DEL SEDEGES).</span></strong></p>
            <p style="margin-left: 18.0pt;"><!-- [if !supportLists]--><strong><span>9.1<span>&nbsp; </span></span></strong><!--[endif]--><strong><span>DERECHOS DEL SEDEGES. -</span></strong></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>a)<span>&nbsp; </span></span></strong><!--[endif]--><span>Controlar y supervisar los servicios prestados por <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong>, debiendo cumplirse con los principios de eficiencia, eficacia, calidad, calidez, econom&iacute;a y &eacute;tica, guardando la debida confidencialidad y dedicaci&oacute;n.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>b)<span>&nbsp; </span></span></strong><!--[endif]--><span>Evaluar <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong> peri&oacute;dicamente, esta funci&oacute;n est&aacute; a cargo del Titular de la Unidad solicitante; en caso de que &eacute;ste considere que <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }} </strong>desempe&ntilde;a funciones de forma deficiente y/o negligente, informar&aacute; a la Directora Departamental del SEDEGES BENI, para los fines que corresponda.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>c)<span>&nbsp; </span></span></strong><!--[endif]--><span>Cumplir todo lo establecido en el Reglamento Interno de Personal del Gobierno Aut&oacute;nomo Departamental del Beni.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>d)<span>&nbsp; </span></span></strong><!--[endif]--><span>Requerir a <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong> los informes, aclaraciones y ampliaciones, que considere necesarias, respecto a los servicios y funciones que preste <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong>.</span></p>
            <br>
            <p style="margin: 0cm 0cm 0cm 18.0pt;"><!-- [if !supportLists]--><strong><span>9.2<span>&nbsp; </span></span></strong><!--[endif]--><strong><span>DEBERES DEL SEDEGES BENI. -</span></strong></p>
            <br>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>a)<span>&nbsp; </span></span></strong><!--[endif]--><span>Proporcionar a <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong> todo apoyo log&iacute;stico, comunicaciones, equipos, material de escritorio y acceso a la informaci&oacute;n necesaria para el desarrollo de su trabajo.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>b)<span>&nbsp; </span></span></strong><!--[endif]--><span>Efectuar los pagos como contraprestaci&oacute;n a favor de <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong>, de conformidad con la Cl&aacute;usula Quinta del presente Contrato.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>c)<span>&nbsp; </span></span></strong><!--[endif]--><span>Proporcionar los pasajes y vi&aacute;ticos necesarios para el cumplimiento de las actividades cuando <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong> sea declarado (a) en comisi&oacute;n oficial, conforme a normativa legal vigente.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>d)<span>&nbsp; </span></span></strong><!--[endif]--><span>Realizar los descuentos establecidos por la Ley de Pensiones N&ordm; 065, de 10 de diciembre de 2010, destinados para los aportes al Seguro a Largo Plazo en beneficio de <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong>.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>e)<span>&nbsp; </span></span></strong><!--[endif]--><span>Asegurar a <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong>, en el Seguro a Corto Plazo, en el Ente Gestor de Salud, del <strong>SEDEGES - Beni</strong>.</span></p>
            
            <p style="margin-left: 0cm; mso-add-space: auto;"><strong><span>CL&Aacute;USULA D&Eacute;CIMA.- DERECHOS Y DEBERES {{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'DE LA CONTRATADA' }}.</span></strong></p>
            
            <p style="margin: 0cm 0cm 0cm 18.0pt;"><!-- [if !supportLists]--><strong><span style="font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial; display: none; mso-hide: all;">10.1<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></strong><!--[endif]--><strong><span>DERECHOS DEL {{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</span></strong></p>
            <p style="mso-add-space: auto; line-height: normal; margin: 0cm 0cm 0cm 14.2pt;"><strong><span>&nbsp;</span></strong></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span style="">a)<span>&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Percibir mensualmente la remuneraci&oacute;n establecida como contraprestaci&oacute;n por sus servicios, en las condiciones se&ntilde;aladas en el presente Contrato. </span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span style="">b)<span>&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Por onom&aacute;stico se conceder&aacute; una jornada de tolerancia de trabajo, con percepci&oacute;n del 100% (cien por ciento) de goce de haberes, siempre que el mismo coincida con una fecha laborable, derecho que debe ser utilizado ese mismo d&iacute;a y no ser&aacute; transferible a otro d&iacute;a.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span style="">c)<span>&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Para atenci&oacute;n de casos particulares, el Contratado contar&aacute; con permiso sin goce de haberes, hasta 3 (tres) d&iacute;as h&aacute;biles, previa autorizaci&oacute;n del Jefe inmediato superior o jer&aacute;rquico, durante la Gesti&oacute;n Fiscal.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span style="">d)<span>&nbsp;&nbsp; </span></span></strong><!--[endif]--><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">Tendr&aacute;n derecho a licencias con goce del 100% (cien por ciento) de sus haberes en los siguientes casos:</span></p>
            <p style="margin: 0cm 0cm 0cm 35.45pt;"><!-- [if !supportLists]--><strong><span>1)<span>&nbsp; </span></span></strong><!--[endif]--><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">Por maternidad, conforme a las disposiciones del C&oacute;digo de Seguridad Social y otras que rigen la materia.</span></p>
            <p style="margin: 0cm 0cm 0cm 35.45pt;"><!-- [if !supportLists]--><strong><span>2)<span>&nbsp; </span></span></strong><!--[endif]--><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">Asistencia a becas y cursos de capacitaci&oacute;n, seminarios de actualizaci&oacute;n y cursos de Post Grado con o sin patrocinio institucional.</span></p>
            <p style="margin: 0cm 0cm 0cm 35.45pt;"><!-- [if !supportLists]--><strong><span>3)<span>&nbsp; </span></span></strong><!--[endif]--><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">Por matrimonio, gozar&aacute; de 3 (tres) d&iacute;as h&aacute;biles, inmediatos al acontecimiento debiendo presentar copia del Certificado de Matrimonio o del Certificado de Inscripci&oacute;n expedida por el Oficial de Registro Civil que acredite la fecha de realizaci&oacute;n del Matrimonio, dentro de los cinco (5) d&iacute;as h&aacute;biles siguientes.</span></p>
            <p style="margin: 0cm 0cm 0cm 35.45pt;"><!-- [if !supportLists]--><strong><span>4)<span>&nbsp; </span></span></strong><!--[endif]--><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">Por fallecimiento de padres, c&oacute;nyuge, hermanos o hijos, 3 (tres) d&iacute;as h&aacute;biles de licencia inmediatos al hecho; de los padres pol&iacute;ticos, hermanos pol&iacute;ticos y/o abuelos, 2 (dos) d&iacute;as h&aacute;biles inmediatos al hecho; debiendo el Servidor o Servidora p&uacute;blica, presentar en copias el Certificado de Defunci&oacute;n pertinente, dentro de los siguientes 5 (cinco) d&iacute;as h&aacute;biles siguientes de ocurrido el suceso.</span></p>
            <p style="margin: 0cm 0cm 0cm 35.45pt;"><!-- [if !supportLists]--><strong><span>5)<span>&nbsp; </span></span></strong><!--[endif]--><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">Por enfermedad o invalidez, se otorgar&aacute; las licencias respectivas seg&uacute;n el R&eacute;gimen de Seguridad Social y se justificar&aacute;n con el Parte de Baja, otorgado por el ente gestor de salud respectivo. Es preciso mencionar qu&eacute;, en caso de enfermedad para efectos de Control de Asistencia, no ser&aacute;n consideradas, ni tendr&aacute;n validez alguna, Certificados o Bajas M&eacute;dicas extendidas por otras instituciones o m&eacute;dicos particulares, solo se podr&aacute; acreditar la misma por el ente gestor de salud del </span><strong><span>SEDEGES - Beni</span></strong><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">.</span></p>
            <p style="margin: 0cm 0cm 0cm 35.45pt;"><!-- [if !supportLists]--><strong><span>6)<span>&nbsp; </span></span></strong><!--[endif]--><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">Por atenci&oacute;n m&eacute;dica de la Servidora o Servidor p&uacute;blico, en casos de emergencia o intervenciones quir&uacute;rgicas respaldados con el Parte de Baja, correspondiente del ente gestor de salud del </span><strong><span>SEDEGES - Beni</span></strong><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">.</span></p>
            <p style="margin: 0cm 0cm 0cm 35.45pt;"><!-- [if !supportLists]--><strong><span>7)<span>&nbsp; </span></span></strong><!--[endif]--><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">Las Contratadas gozar&aacute;n de licencia remunerada de un (1) d&iacute;a h&aacute;bil al a&ntilde;o, divisible en dos medias jornadas, a objeto de someterse a un examen m&eacute;dico y lectura de los resultados del examen Papanicolaou, Mamograf&iacute;a y otros.</span></p>
            <p style="margin: 0cm 0cm 0cm 35.45pt;"><!-- [if !supportLists]--><strong><span>8)<span>&nbsp; </span></span></strong><!--[endif]--><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">En el caso de nacimiento de hijos, el padre progenitor gozar&aacute; de 3 (tres) d&iacute;as h&aacute;biles de licencia a partir del alumbramiento de la conyugue o conviviente, con la obligaci&oacute;n de presentar el Certificado correspondiente, dentro los cinco (5) d&iacute;as h&aacute;biles siguientes.</span></p>
            <p style="margin: 0cm 0cm 0cm 35.45pt;"><!-- [if !supportLists]--><strong><span>9)<span>&nbsp; </span></span></strong><!--[endif]--><span style="font-family: 'Arial',sans-serif; mso-bidi-font-weight: bold;">En aquellos casos que no se ha determinado plazos de presentaci&oacute;n de la documentaci&oacute;n respaldatoria pertinente, seg&uacute;n corresponda, deber&aacute; ser presentada al &aacute;rea de Recursos Humanos en el plazo m&aacute;ximo de los 3 (tres) d&iacute;as h&aacute;biles siguientes a la licencia. En caso de no presentar la documentaci&oacute;n respectiva en los plazos establecidos, los d&iacute;as utilizados como licencia ser&aacute;n considerados como permiso sin goce de haberes. Toda licencia deber&aacute; ser otorgada y autorizada de forma escrita por el Jefe inmediato superior y/o el superior jer&aacute;rquico.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span style="">e)<span>&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Recibir un ambiente de infraestructura y laboral adecuado para el desempe&ntilde;o de sus funciones.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span style="">f)<span>&nbsp;&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Cuando la naturaleza de las funciones que desarrolla {{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}; as&iacute; lo requiera, podr&aacute; solicitar control alternativo al Control Biom&eacute;trico.</span></p>
            <br>
            <p style="margin: 0cm 0cm 0cm 18.0pt;"><!-- [if !supportLists]--><strong><span>10.2<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></strong><!--[endif]--><strong><span>OBLIGACIONES DE {{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</span></strong></p>
            <br>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>a)<span>&nbsp; </span></span></strong><!--[endif]--><span>Cumplir con todas las Cl&aacute;usulas estipuladas en el presente Contrato. </span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>b)<span>&nbsp; </span></span></strong><!--[endif]--><span><strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong> se encuentra sujeto al pago <strong>RC-IVA</strong>, y debe presentar en forma mensual la respectiva Declaraci&oacute;n Jurada en el formulario correspondiente al &Aacute;rea de Recursos Humanos del SEDEGES para efectos de cr&eacute;dito fiscal, con las excepciones de ley. (Cuando corresponda).</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>c)<span>&nbsp; </span></span></strong><!--[endif]--><span>Prestar los servicios, objeto del presente Contrato, conforme a los principios de: Eficiencia, eficacia, econom&iacute;a, &eacute;tica e integridad profesional; debiendo demostrar diligencia e idoneidad durante el desarrollo de la prestaci&oacute;n de sus servicios, aplicando los m&eacute;todos y procedimientos m&aacute;s convenientes para el cumplimiento de sus obligaciones.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>d)<span>&nbsp; </span></span></strong><!--[endif]--><span>En caso de retiro o cualquier forma de desvinculaci&oacute;n de servicios entre el <strong>SEDEGES - Beni y {{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }},</strong> &eacute;ste tiene la obligaci&oacute;n de presentar un detalle de toda la documentaci&oacute;n que se encontraba a su cargo, se&ntilde;alar los tr&aacute;mites pendientes y en qu&eacute; situaci&oacute;n se encuentran estos.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>e)<span>&nbsp; </span></span></strong><!--[endif]--><span>Brindar dedicaci&oacute;n exclusiva, durante la vigencia del Contrato y dar cumplimiento de la Misi&oacute;n Espec&iacute;fica.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>f)<span>&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Efectuar las aclaraciones y/o ampliaciones que el <strong>SEDEGES - Beni</strong> estime necesarias acerca de sus informes y de las actividades que hubiese realizado.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>g)<span>&nbsp; </span></span></strong><!--[endif]--><span>Conservar, cuidar, preservar y salvaguardar los bienes (equipos y mobiliarios), que le sean asignados por el <strong>SEDEGE S- Beni</strong>, para el cumplimiento de sus funciones, teniendo la obligaci&oacute;n de solicitar al Responsable de Activos fijos, tanto la asignaci&oacute;n y devoluci&oacute;n de los Activos.<u></u></span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>h)<span>&nbsp; </span></span></strong><!--[endif]--><strong><span>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</span></strong><span> est&aacute; obligado a cumplir con los Instructivos, Circulares y/o Memor&aacute;ndums de asignaci&oacute;n de funciones que le asigne el Jefe de su Unidad o inmediato superior, el Jefe de Administraci&oacute;n y Finanzas, Jefe de Unidad Jur&iacute;dica y/o el Director(a) del Servicio Departamental de Gesti&oacute;n Social <strong>SEDEGES - Beni</strong>. El incumplimiento de este par&aacute;grafo ser&aacute; pasible a un Memor&aacute;ndum de llamada de atenci&oacute;n.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>i)<span>&nbsp;&nbsp;&nbsp; </span></span></strong><!--[endif]--><strong><span>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</span></strong><span> est&aacute; obligado a realizar los Descargos Respectivos dentro del plazo legal establecido, de los Recursos asignados por concepto de vi&aacute;ticos y/o fondos en avance. El incumplimiento de este par&aacute;grafo ser&aacute; pasible a un Memor&aacute;ndum de llamada de atenci&oacute;n, adem&aacute;s de la retenci&oacute;n de hasta el 20% (veinte por ciento) de su haber mensual hasta la reposici&oacute;n del monto asignado.</span></p>
            <p class="MsoListParagraphCxSpLast" style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>j)<span>&nbsp;&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Proceder a la devoluci&oacute;n de los activos fijos, materiales, que hubieran sido otorgados por el <strong>SEDEGES- Beni</strong> y documentaci&oacute;n a su cargo en formato f&iacute;sico y digital, una vez terminado y/o resuelto el presente Contrato.</span></p>
            
            <p><strong><span>CL&Aacute;USULA D&Eacute;CIMA PRIMERA. - (DEL INCUMPLIMIENTO Y LAS SANCIONES).</span></strong></p>
            
            <p><strong><span>11.1 </span></strong><span>Si durante la vigencia de este Contrato <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong> incumpliera, en todo o en parte con lo pactado, el <strong>SEDEGES- Beni</strong> podr&aacute; iniciar en su contra las acciones administrativas, judiciales, extrajudiciales que a su juicio correspondan; dada la naturaleza jur&iacute;dica del presente Contrato y lo estipulado en la Ley de Administraci&oacute;n y Control Gubernamental N&ordm; 1178 de 20 de julio de 1990, adem&aacute;s de sus normas reglamentarias o las que fueren aprobadas durante la vigencia de este Contrato, debiendo asumir <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong> la responsabilidad que ameriten los resultados emergentes del desempe&ntilde;o de sus funciones, deberes y atribuciones, as&iacute; como los da&ntilde;os y perjuicios ocasionados.</span></p>
            <p><span>Asimismo, se hace constar, que el mecanismo de sancionar una falta administrativa cometida por <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong> ser&aacute; mediante Memor&aacute;ndum de llamada de atenci&oacute;n, no librando de las otras responsabilidades que emerjan del hecho sancionado.</span></p>
            
            <p><strong><span>11.2 (INFRACCIONES Y SANCIONES DICIPLINARIAS).-</span></strong></p>
            <p><span>El presente Contrato de Personal Eventual, contempla adicionalmente el siguiente R&eacute;gimen Disciplinario: </span></p>
            <p><strong><span>a) Sanciones Leves </span></strong></p>
            <p><strong><span>b) Sanciones Graves </span></strong></p>
            <p><strong><span>c) Sanciones Severas.</span></strong></p>
            
            <p><strong><span>11.2.1 SANCIONES LEVES. - </span></strong><span>Es la llamada de atenci&oacute;n verbal realizada por el Jefe inmediato superior o superior jer&aacute;rquico, que se hace al Servidor o Servidora p&uacute;blica, respecto a la falta cometida originada en siguientes casos:</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>a)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por incumplir los principios, derechos, deberes, prohibiciones, incompatibilidades y en general cualquier Cl&aacute;usula del presente Contrato de Personal Eventual.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>b)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por negligencia o retardo en el cumplimiento de los deberes inherentes al puesto.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>c)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por no respetar el orden jer&aacute;rquico establecido y/ o el conducto regular.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>d)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por desorden o descuido en el manejo de documentos, materiales y &uacute;tiles de trabajo.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>e)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por incumplimiento a la obligaci&oacute;n de constituirse en su puesto de trabajo e iniciar el mismo inmediatamente despu&eacute;s de haber registrado su ingreso a la entidad.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>f)<span>&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Dar uso inadecuado de equipos, materiales y otros activos del &aacute;rea de trabajo.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>g)<span>&nbsp; </span></span></strong><!--[endif]--><span>No permanecer en su sitio de trabajo o instalaciones del <strong>SEDEGES</strong> <strong>&ndash; Beni,</strong> en el horario establecido como jornada laboral.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>h)<span>&nbsp; </span></span></strong><!--[endif]--><span>Agresi&oacute;n verbal, que consiste en toda expresi&oacute;n o ataque verbal, que de forma directa realiza una persona hacia otra por motivos racistas o discriminatorios con la intenci&oacute;n de ofender su dignidad como ser humano.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>i)<span>&nbsp;&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>No asistir y/ o reprobar cursos, seminarios, conferencias y otros eventos patrocinados por la entidad.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>j)<span>&nbsp;&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Fumar en &aacute;reas cerradas, ba&ntilde;os o ambientes dependientes de la Instituci&oacute;n.</span></p>
            <p class="MsoListParagraphCxSpLast" style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>k)<span>&nbsp; </span></span></strong><!--[endif]--><span>Ingresar a instalaciones del <strong>SEDEGES</strong> <strong>&ndash; Beni</strong>, en fines de semana o feriados, sin autorizaci&oacute;n respectiva.</span></p>
            <p><strong><span>11.2.2 SANCIONES GRAVES. - </span></strong><span>Es la llamada de atenci&oacute;n formal que origina una amonestaci&oacute;n escrita &ldquo;Memor&aacute;ndum de Severa Llamada de Atenci&oacute;n&rdquo; realizado por el Director(a) del SEDEGES-BENI, a solicitud del Jefe inmediato superior que ser&aacute;n aplicadas en los siguientes casos:</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>a)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por faltar el respeto a los Superiores Jer&aacute;rquicos o compa&ntilde;eros de trabajo, de hecho, por escrito o de palabra.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>b)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por actos de racismo y toda forma de discriminaci&oacute;n (agresiones verbales, denegaci&oacute;n de acceso al servicio, maltrato f&iacute;sico, psicol&oacute;gico y sexual) que constituyan faltas cometidas por Servidoras y Servidores p&uacute;blicos.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>c)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por no respetar y cumplir disposiciones administrativas (Resoluciones, Memor&aacute;ndums, Instructivos, Circulares y Otras).</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>d)<span>&nbsp; </span></span></strong><!--[endif]--><span>No acatar las determinaciones de sus Superiores Jer&aacute;rquicos, enmarcadas en la Ley.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>e)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por incumplimiento de funciones.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>f)<span>&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Por incumplimiento reiterado de &oacute;rdenes del Inmediato Superior o Superior Jer&aacute;rquico y obligaciones funcionarias instruidas por escrito o por la no ejecuci&oacute;n de las mismas, ya sea por negligencia u omisi&oacute;n.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>g)<span>&nbsp; </span></span></strong><!--[endif]--><span>Utilizar bienes o recursos p&uacute;blicos de la Instituci&oacute;n en objetivos pol&iacute;ticos, particulares o de cualquier otra naturaleza que no sea compatible con la espec&iacute;fica actividad funcionaria.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>h)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por reincidir tres (3) veces en infracciones leves.</span></p>
            <p class="MsoListParagraphCxSpLast" style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>i)<span>&nbsp;&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Contratar a Servidoras o Servidores p&uacute;blicos de la entidad o personas ajenas a &eacute;l, por cuenta propia, para la realizaci&oacute;n de labores propias de su cargo.</span></p>
            
            <p><strong><span>11.2.3 SANCIONES SEVERAS. - </span></strong><span>Son aquellas medidas que se aplican como resultado de situaciones muy graves, flagrantes o extremas, cuyos resultados ser&iacute;an tales como la: </span></p>
            <p><strong><span>a)</span></strong><span> Destituci&oacute;n sin Proceso Sumario </span></p>
            <p><strong><span>b)</span></strong><span> Destituci&oacute;n con Proceso Sumario.</span></p>
            <p><strong><span>11.3 SANCIONES POR FALTAS. - </span></strong><span>La sanci&oacute;n por falta de registro de asistencia en el horario de ingreso a la entidad ya sea en el turno de la ma&ntilde;ana o de la tarde, ser&aacute; considerada como falta (inasistencia al trabajo), y &uacute;nicamente por la primera vez, se descontar&aacute; medio d&iacute;a de haber. A partir de la segunda falta de registro el descuento se regir&aacute; a la escala definida en EL REGLAMENTO DE Personal del Gobierno Aut&oacute;nomo Departamental del Beni.</span></p>
            <p><strong><span>11.4 SANCIONES POR ABANDONO. - </span></strong><span>La sanci&oacute;n por abandono, se rige de acuerdo al Reglamento Interno de Personal del Gobierno Aut&oacute;nomo Departamental del Beni.</span></p>
            <p><strong><span>11.5</span></strong><span> Cuando <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong>, consuma o llegue a su fuente laboral en estado de ebriedad o bajo influencias alcoh&oacute;licas, evidente y/o habiendo consumido sustancias il&iacute;citas no se le permitir&aacute; el ingreso ni la permanencia en la entidad, siendo considerada esta como la inasistencia injustificada, procedi&eacute;ndose al descuento equivalente a tres (3) d&iacute;as de su haber mensual.</span></p>
            
            <p><strong><span>CL&Aacute;USULA D&Eacute;CIMA SEGUNDA. - (CAUSALES DE RESOLUCI&Oacute;N DEL CONTRATO)</span></strong></p>
            <p><strong><span>El SEDEGES BENI &nbsp;o {{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }},</span></strong><span> podr&aacute;n requerir la Resoluci&oacute;n del presente Contrato sin necesidad de requerimiento judicial o extrajudicial, por lo siguientes motivos:</span></p>
            <p style="margin-left: 18.75pt; mso-add-space: auto; text-indent: -18.75pt; mso-list: l4 level2 lfo14;"><!-- [if !supportLists]--><strong><span>12.1<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></strong><!--[endif]--><strong><span>POR PARTE DEL SEDEGES</span></strong></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>a)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por ac&uacute;mulo de dos (2) llamadas de atenci&oacute;n (graves) por incumplimiento de sus obligaciones y/o por omisi&oacute;n, negligencia o descuido en las mismas, durante un mismo mes.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>b)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por p&eacute;rdida, da&ntilde;o o merma de bienes otorgados en custodia a <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong>, a causa de su negligencia y/o impericia al momento de manipular el bien que se le sea asignado para el desarrollo de sus funciones.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>c)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por tres (3) faltas continuas o seis (6) discontinuas durante la vigencia del contrato.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>d)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por reincidencia en asistir a su fuente laboral, bajo influencias de bebidas alcoh&oacute;licas, sustancias controladas, estupefacientes y psicotr&oacute;picas o consumir las mismas en instalaciones del <strong>SEDEGES - Beni</strong>.</span></p>
            <p style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>e)<span>&nbsp; </span></span></strong><!--[endif]--><span>Por reprobar en dos (2) oportunidades consecutivas alg&uacute;n curso impartido por la Contralor&iacute;a General de Estado o cualquier otro curso que patrocine el <strong>SEDEGES - Beni</strong>.</span></p>
            <p class="MsoListParagraphCxSpLast" style="margin: 0cm 0cm 0cm 14.2pt;"><!-- [if !supportLists]--><strong><span>f)<span>&nbsp;&nbsp; </span></span></strong><!--[endif]--><span>Por negligencia demostrada en el cumplimiento de sus deberes que tengan como resultado el da&ntilde;o econ&oacute;mico al Estado y a la Instituci&oacute;n o el desprestigio de &eacute;sta.</span></p>        
            <p><strong><span>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}&nbsp;&nbsp; </span></strong><span>asume la voluntad de no podr&aacute; abandonar su fuente laboral mientras no sea notificado con &nbsp;la Resoluci&oacute;n de Contrato respectiva y entregue todos los requisitos exigidos, para tal efecto.</span></p>
            <p><strong><span>12.2 POR MUTUO ACUERDO.</span></strong></p>
            <p><span>Por acuerdo mutuo entre el <strong>SEDEGES &ndash; Beni</strong> y {{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}, este &uacute;ltimo dar&aacute; aviso escrito al CONTRATANTE solicitando la Resoluci&oacute;n del Contrato, previa entrega de los informes correspondientes, activos fijos, toda otra documentaci&oacute;n.</span></p>        
            <p><strong><span>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }} </span></strong><span>asume la voluntad de no abandonar su fuente laboral mientras no reciba la Resoluci&oacute;n de Contrato, respectiva</span></p>
            <p><strong><span>12.3 POR CASOS DE FUERZA MAYOR O CASO FORTUITO.</span></strong></p>
            <p><strong><span>Se entender&aacute; por hechos de Fuerza Mayor, Caso Fortuito u otras causas debidamente justificas</span></strong><span>, como aquellos eventos que se encuentren fuera del alcance del <strong>SEDEGES - Beni</strong> y del <strong>CONTRATADO (A),</strong> imprevisibles o inevitables que se encuentren fuera del control y voluntad de las partes, haciendo imposible el cumplimiento de las obligaciones dentro de las condiciones inicialmente pactadas. Los hechos de Fuerza Mayor, Caso Fortuito u otras causas debidamente justificas, incluyen y no se limitan a: Incendios, inundaciones, desastres naturales, conmociones civiles, huelgas, bloqueos y/o revoluciones o cualquier otro hecho que afecte el cumplimiento de las obligaciones inicialmente pactadas y que no tenga como origen la negligencia o falta de cuidado de las partes intervinientes dentro del presente Contrato.</span></p>
            <p><span>De presentarse una situaci&oacute;n de fuerza mayor o caso fortuito por parte del <strong>SEDEGES - Beni</strong>, este notificar&aacute; prontamente y por escrito a <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }} </strong>sobre dicha situaci&oacute;n y sus causas. En este caso ni el <strong>SEDEGES &ndash;Beni </strong>ni <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }} </strong>estar&aacute;n sujetos a sanciones de ning&uacute;n tipo, liquidaci&oacute;n por da&ntilde;os y perjuicios o a la Resoluci&oacute;n del Contrato por incumplimiento. </span></p>
            <p><strong><span>12.4 PROCEDIMIENTO PARA EFECTUAR LA RESOLUCI&Oacute;N</span></strong></p>
            <p><span>De ocurrir una de las causales anteriormente se&ntilde;aladas, cualquiera de las partes podr&aacute; notificar a la otra su decisi&oacute;n de resolver el Contrato, especificando la causa en que se funda.</span></p>
            <p><strong><span>12.5 EFECTOS DE LA RESOLUCI&Oacute;N</span></strong></p>
            <p><span>En caso de producirse la Resoluci&oacute;n del Contrato, se proceder&aacute; a la liquidaci&oacute;n de saldos deudores y acreedores de ambas partes, efectu&aacute;ndose los pagos a que hubiere lugar, para dicho fin <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong> autoriza al <strong>SEDEGES -Beni</strong> realizar los descuentos pertinentes de su &uacute;ltima Boleta de Pago, cuando hubiere lugar a descuentos.</span></p>
            
            <p><strong><span>CL&Aacute;USULA D&Eacute;CIMA TERCERA. - (DE LA CONFIDENCIALIDAD EN EL TRABAJO).</span></strong></p>
            <p><span>Los materiales producidos por {{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }} dentro el cumplimiento de sus funciones, as&iacute; como la informaci&oacute;n a la que este tuviera acceso, durante o despu&eacute;s de la ejecuci&oacute;n del presente Contrato, tendr&aacute;n car&aacute;cter CONFIDENCIAL quedando expresamente prohibida su divulgaci&oacute;n a terceros por parte de <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }},</strong> a menos que cuente con una autorizaci&oacute;n escrita del <strong>SEDEGES</strong> &ndash; <strong>Beni </strong>en sentido contrario. Asimismo, los derechos de autor que emerjan de los trabajos realizados por <strong>{{ $contract->person->gender == 'masculino' ? 'EL CONTRATADO' : 'LA CONTRATADA' }}</strong> ser&aacute;n exclusiva propiedad del <strong>SEDEGES -&nbsp; Beni</strong>.</span></p>
            <p><strong><span>CL&Aacute;USULA D&Eacute;CIMA CUARTA. - (DE LA PREVISI&Oacute;N).</span></strong></p>
            <p><span>El presente Contrato Administrativo de Prestaci&oacute;n de Servicios de Personal Eventual podr&aacute; ser modificado previo acuerdo entre las partes, dichas modificaciones deber&aacute;n estar orientadas y destinadas al cumplimiento del Objeto de la contrataci&oacute;n, debiendo estar sustentadas por Informe T&eacute;cnico y Legal que establezcan la viabilidad t&eacute;cnica y de financiamiento.</span></p>
            
            <p><strong><span>CL&Aacute;USULA D&Eacute;CIMA QUINTA. - (ACEPTACI&Oacute;N Y CONFORMIDAD).</span></strong></p>
            <p><span style="font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: ES-BO; mso-fareast-language: ES; mso-bidi-language: AR-SA;">Las partes intervinientes declaran su plena conformidad con el contenido de las Cl&aacute;usulas estipuladas en el presente Contrato, firmando en cuatro (4) ejemplares de un mismo tenor y validez por la/el <strong>{{ $signature ? $signature->name : setting('firma-autorizada.name') }}, </strong>con C&eacute;dula de Identidad <strong>N&ordm; {{ $signature ? $signature->ci : setting('firma-autorizada.ci') }}</strong>, en representaci&oacute;n Legal del <strong>SERVICIO DEPARTAMENTAL DE GESTION SOCIAL (SEDEGES-Beni);</strong> y por otra parte, {{ $contract->person->gender == 'masculino' ? 'el señor' : 'la señora' }} {{ $contract->person->first_name }} {{ $contract->person->last_name }} con C&eacute;dula de Identidad N&ordm;  {{ $contract->person->ci }} como CONTRATADO. &Eacute;ste documento, conforme a disposiciones legales de control fiscal vigente, ser&aacute; registrado ante la Contralor&iacute;a General del Estado en idioma Espa&ntilde;ol.</span></p>
            <br>
            <p style="text-align: right;">
                <span>{{ Str::upper($contract->direccion_administrativa->city ? $contract->direccion_administrativa->city->name : 'Santísima Trinidad') }}</span>, {{ date('d', strtotime($contract->start)) }} de {{ Str::upper($months[intval(date('m', strtotime($contract->start)))]) }} de {{ date('Y', strtotime($contract->start)) }}
            </p>
            <table class="table-signature">
                <tr>
                    <td style="width: 50%">
                        {{-- ....................................................... <br>
                        {{ $signature ? $signature->name : setting('firma-autorizada.name') }} <br>
                        <b>{{ Str::upper($signature ? $signature->job : setting('firma-autorizada.job')) }}</b> --}}
                    </td>
                    <td style="width: 50%">
                        ....................................................... <br>
                        {{ $contract->person->gender == 'masculino' ? 'Sr.' : 'Sra.' }} </em><em>{{ $contract->person->first_name }} {{ $contract->person->last_name }} <br>
                        <b>{{ $contract->person->gender == 'masculino' ? 'CONTRATADO' : 'CONTRATADA' }}</b>
                    </td>
                </tr>
            </table>

        </div>
    @endif
@endsection

@section('css')
    <style>
        
    </style>
@endsection

@section('script')
    <script>

    </script>
@endsection